fix(vite-node): Prevent crash when passing single module as options
Right now, when passing a single module with the new `--options` CLI flag, `cac` returns a string instead of an array. This causes a crash, trying to call `map` on it.

```
❯ ./packages/vite-node/vite-node.mjs --options.deps.inline="module" hello.js
file:///Users/antoine/Code/vitest/packages/vite-node/dist/cli.js:697
      inline: (_b = (_a = serverOptions.deps) == null ? void 0 : _a.inline) == null ? void 0 : _b.map((dep) => {
                                                                                                  ^

TypeError: _b.map is not a function
    at parseServerOptions (file:///Users/antoine/Code/vitest/packages/vite-node/dist/cli.js:697:99)
    at CAC.run (file:///Users/antoine/Code/vitest/packages/vite-node/dist/cli.js:660:49)
    at CAC.runMatchedCommand (file:///Users/antoine/Code/vitest/packages/vite-node/dist/cli.js:622:34)
    at CAC.parse (file:///Users/antoine/Code/vitest/packages/vite-node/dist/cli.js:549:12)
    at file:///Users/antoine/Code/vitest/packages/vite-node/dist/cli.js:652:5
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
```

This PR updates the typings to reflect that, and makes sure that both `string` and `string[]` are properly handled.